# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tastmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tastModel',
            new_name='TestModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published')], default='draft', max_length=10),
        ),
    ]
