# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170312_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', '未发布'), ('p', '已发布')], default='d', max_length=10),
        ),
    ]
