# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170426_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
