# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniLibrary', '0012_auto_20170420_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='red', max_length=10),
        ),
    ]
